### ISSUE TITLE
Needs Readme :)

### ISSUE THREAD

**Issue by CorySpitzer** [idupree/hilarious-text-editor#1]
I managed to launch it, but how do I do all the other things?

A Readme could tell me :)

**Comment by idupree** [comment]
hahaha yes it does

currently, go to http://localhost:3419/ while it's running

but "all the other things" is-- about nothing, right now. It autosaves continously to the test save file but that's it. More features soon and then I'll be able to document them :)

The motivating reason for this project is that Dragon NaturallySpeaking is pretty effective at controlling HTML &lt;textarea>s in IE 11, and @elidupree needs a text editor for zir code that has fewer misfeatures for the purposes of code editing than DragonPad or Word.  It might be useful for other things but that's the main point.  This statement will go in the README.md once it exists.  It could integrate something like http://ace.c9.io/ as an editor, but it probably won't because Dragon gets a little confused by the fancy things those editors do (in ace editor, for example, most of the text in the document is not in the &lt;textarea> element at any given time, but is instead in other elements.  Presumably so they can syntax hilight it and/or be more asymptotically efficient at editing.  CodeMirror editor - used for example by twine2 - I am even less sure what exactly it's doing in the DOM.)

**Comment by idupree** [comment]
README is added! And many of the features are implemented... it might be somewhat useful now. :)

**Comment by CorySpitzer** [comment]
Sweet :)
